build:
  maxIssues: 0

complexity:
  LongMethod:
    threshold: 80
    ignoreAnnotated: ['Composable']
  CyclomaticComplexMethod:
    ignoreAnnotated: ['Composable']
  LongParameterList:
    functionThreshold: 8

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']

style:
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreAnnotation: true
    ignoreEnums: true
    ignoreAnnotated: ['Composable']

formatting:
  active: true
  android: true
  autoCorrect: false
